### ISSUE TITLE
margin的一些笔记

### ISSUE THREAD

**Issue by myLB** [myLB/learngit#3]
# 元素尺寸

       1、可视尺寸-clientWidth（标准）——就是上图中的border box包含的尺寸。

       2、占据尺寸-outerWidth（YY，jQuery里面是有这个方法的）——就是上图中的margin box包含的尺寸。

# margin与可视尺寸
 ## 此规则的适用范围：
       1、适用于 没有设定width/height 的 普通 block水平 元素。不包括（float元素 absolute/fixed元素 inline水平，table-cell元素，…）

       2、只适用于水平方向的尺寸。
![wx20180317-201458](https://user-images.githubusercontent.com/22436601/37555268-f1a57664-2a1f-11e8-8e62-a11ac1bb31bc.png)`
   
```css 
 div {
   overflow: hidden;
   background: #000;
 }

 p {
    height: 200px;
    margin: 50px 50px;
   background: #4794ea;
 }
````

# margin进行等高布局
**原理：通过padding设置盒模型变大然后通过margin负值改变元素占据空间（前提不设置高度）**
 
```css 
 list1 {
   padding-bottom: 3000px;
   margin-bottom: -3000px;
 }
 list2 {
   padding-bottom: 3000px;
   margin-bottom: -3000px;
 }
````
# margin进行两端对齐布局
**原理：通过margin负值拉伸没有定宽的块元素**
```html
<div class="box">
   <ul> 
     <li></li>
     <li></li>
     <li></li>
   </ul>
</div>
````
```less
.box {
    background-color: orange;
    margin: auto;
    width: 900px;
    ul {
      margin-right: -20px;
      overflow: hidden;
      li {
        width: 280px;
        height: 300px;
        margin-right: 20px;
        float: left;
        background-color: green;
      }
    }
  }
```
# margin负值的一些原理

     margin负值的百分比是基于父元素的内容宽度，不包括父元素的padding、margin。

## 负边距对浮动元素的影响
   margin负值足够大时,大到负值大于元素自身的宽度(包括padding)时，会使元素的占有宽度为0，相当于不占据位置，如果这个时候加个浮动会使元素上浮动，与上一个宽度为100%的浮动元素同级。
> 也就是用这种特性实现圣杯或两翼布局等等.
