### ISSUE TITLE
居中布局的一些记录，方便查询记忆

### ISSUE THREAD

**Issue by myLB** [myLB/learngit#4]
# 水平居中

   ## 1、center+inline-block

```html
<div class="parent">
  <div class="child">aiuhsdu</div>
</div>
```
```css
<style>
  .parent {
    text-align: center;
  }
  .child {
    display: inline-block;
  }
</style>
```
## 效果图

![qq 20180328133703](https://user-images.githubusercontent.com/22436601/38010827-4bc798e6-328d-11e8-9b7a-424cfaa6b0df.png)

**影响: 如果父元素或以上的父元素设置了font-size会产生空隙。**

## 2、display: table + margin: 0 auto

```html
<div class="parent">
  <div class="child">aiuhsdu</div>
</div>
```
```css
.parent {
  background-color: orange;
}
.child {
  display: table;
  background-color: green;
  margin: 0 auto;
}
```
## 效果图

![qq 20180328134445](https://user-images.githubusercontent.com/22436601/38011016-35eb5854-328e-11e8-9121-9c4928e88ae7.png)

**影响: 暂无发现**

##  3、absolute + transform: translate(-50%)

**原理：位移是相对于自身的。**
  
```html
<div class="parent">
   我是parent
   <div class="child">我是child</div>
</div>
```
```css
.parent {
  background-color: orange;
  position: relative;
  width: 200px;
  height: 200px;
}
.child {
  position: absolute;
  background-color: green;
  left: 50%;
  transform: translate(-50%);
}
```
## 效果图
![1](https://user-images.githubusercontent.com/22436601/38011383-cb739246-328f-11e8-90ee-7aab9c4424c3.png)

**影响: CSS3属性，兼容性有点问题，但现在大多数都兼容了**

## 4、flex+margin

**原理: 利用flex把子元素转换为flex item，但这个item还是块元素，利用margin: atuo居中**

```html
<div class="parent">
  我是parent
  <div class="child">我是child</div>
</div>
```
```css
.parent {
  background-color: orange;
  display: flex;
}
.child {
  margin: 0 auto;
  background-color: green;
}
```
## 效果图
![2](https://user-images.githubusercontent.com/22436601/38011655-d8161eb4-3290-11e8-89a0-f15243653db9.png)

**影响: 明显可以看到，子元素受到文字的影响，不是绝对的居中，并且兼容性不支持低版本IE(移动端可以用)** 

## 5、flex+justify-content

**原理: justify-content定义设置了flex元素的子元素水平轴居中**

```html
<div class="parent">
  我是parent
  <div class="child">我是child</div>
</div>
```
```css
.parent {
  background-color: orange;
  display: flex;
  justify-content: center;
}
.child {
  background-color: green;
}
```
## 效果图
![qq 20180328133703](https://user-images.githubusercontent.com/22436601/38011879-bb8a6556-3291-11e8-901c-f1ef3e9dfeae.png)

**影响: 暂无，把所有的子元素都居中了**

# 垂直居中
  ##  1、table-cell+vertical-align
 **原理: 通过将父框转化为一个表格单元格显示（类似td和th)**

```html
<div class="parent">
  我是parent
  <div class="child">我是child</div>
</div>
```
```css
.parent {
  background-color: orange;
  display: table-cell;
  height: 100px;
  vertical-align: middle;
}
.child {
  background-color: green;
}
```
## 效果图
![4](https://user-images.githubusercontent.com/22436601/38012303-7be552a6-3293-11e8-9e9c-db501bc44f8b.png)

**影响: 如果父元素中有文本节点，不会完全垂直居中(vertival-aligin: middle是伪居中，它受font的影响，所以在父元素中可以设置font-size: 0; )**

##  2、absolute+transform

```html
<div class="parent">
  我是parent
  <div class="child">我是child</div>
</div>
```
```css
.parent {
  background-color: orange;
  height: 100px;
  position: relative;
}
.child {
  position: absolute;
  transform: translateY(-50%);
  top: 50%;
  background-color: green;
}
```
## 效果图
![222](https://user-images.githubusercontent.com/22436601/38012650-e28dbc4a-3294-11e8-8957-4dd5f52ed07f.png)

**好处:不受兄弟元素的影响，同样适用于水平居中**
**影响:父元素必须设置高度** 

##  3、flex+align-items

```html
<div class="parent">
  我是parent
  <div class="child">我是child</div>
</div>
```
```css
.parent {
  background-color: orange;
  height: 100px;
  display: flex;
  align-items: center;
}
.child {
  background-color: green;
}
```
##  效果图
![2](https://user-images.githubusercontent.com/22436601/38012943-e2a574e2-3295-11e8-8318-0feac1dcb894.png)

**影响: 低版本浏览器不兼容**

# 水平垂直居中

  ##  1、absolute+transform

```html
<div class="parent">
  我是parent
  <div class="child">我是child</div>
</div>
```
```css
.parent {
  background-color: orange;
  height: 100px;
  width: 200px;
  position: relative;
}
.child {
  position: absolute;
  left: 50%;
  top: 50%;
  transform: translate(-50%,-50%);
  background-color: green;
}
```
##  效果图
![21344904](https://user-images.githubusercontent.com/22436601/38013288-2fa2d3ce-3297-11e8-9a8c-0a33eb07ca61.png)

**好处: 不受兄弟元素影响**
**影响： 一定要设置父元素的宽高，除非有其他兄弟元素将父元素撑开。**

## 2、inline-block+text-align+table-cell+vertical-align

**原理：通过table-cell+vertical-align是子元素伪居中，通过设置font-size: 0，真正垂直居中；在使文本居中，在把子元素变成内联元素**

```html
<div class="parent">
  我是parent
  <div class="child">我是child</div>
</div>
```
```css
.parent {
  background-color: orange;
  height: 100px;
  width: 200px;
  font-size: 0;
  display: table-cell;
  vertical-align: middle;
  text-align: center;
}
.child {
  display: inline-block;
  background-color: green;
}
```
## 效果图
![649](https://user-images.githubusercontent.com/22436601/38013588-4453e9ec-3298-11e8-9d82-836ffdd5ec0d.png)
**好处：兼容低版本浏览器**
**影响：受兄弟元素的影响**

## 3、flex+justify-content+align-items

```html
<div class="parent">
  我是parent
  <div class="child">我是child</div>
</div>
```
```css
.parent {
  background-color: orange;
  height: 100px;
  width: 200px;
  display: flex;
  align-items: center;
  justify-content: center;
}
.child {
  background-color: green;
}
```
## 效果图
![50423](https://user-images.githubusercontent.com/22436601/38013877-568200e4-3299-11e8-8e56-f9924bc99524.png)

**影响：受兄弟元素影响，不兼容低版本浏览器**

## 4、absolute
**原理：将元素绝对定位，通过left,top,right,bottom设为0，拉伸盒子,在强行设置盒子的宽高,在通过margin: auto使其水平垂直居中**

```html
<div class="div"></div>
```
```css
html,body {
  height: 100%;
}
.div {
  width:100px;
  height:100px;
  background-color: green;
  float: left;
  position: absolute;
  left: 0;
  top: 0;
  right: 0;
  bottom: 0;
  margin: auto;
}
```
## 效果图
![image](https://user-images.githubusercontent.com/22436601/38071707-75909f92-3355-11e8-8aba-4558f3906e1c.png)

**劣势：元素必须设置宽高**
**优势：兼容性强**
