### ISSUE TITLE
多列布局的一些记录，方便查询记忆

### ISSUE THREAD

**Issue by myLB** [myLB/learngit#5]
# 定宽+自适应
##  1、float+(overflow或margin)

**overflow原理: 左边定宽浮动脱离文档流，右边通过BFC特性,使元素不影响外部元素，自成块** 
**margin原理: 左边定宽浮动脱离文档流，有边通过margin改变右边元素的宽度**

```html
<div class="box">
  <div class="left">
    <p>left</p>
  </div>
  <div class="right">
    <p>right</p>
    <p>right</p>
  </div>
</div>
```
```css
.box {
  overflow: hidden;//清除浮动
}
.left {
  width: 100px;
  float: left;
  background-color: orange;
}
.right {
  overflow: hidden;（或者换成margin-left: 100px;）
  background-color: green;
}
```
## 效果图

![0](https://user-images.githubusercontent.com/22436601/38017963-29ac563e-32a6-11e8-8ede-d679df99457c.png)

**好处：方便，兼容性强**
**坏处：暂无**

## 2、table
**原理：通过将父框设置为表格，将左右边框转化为类似于同一行的td，从而达到多列布局**

```html
<div class="box">
  <div class="left">
    <p>left</p>
  </div>
  <div class="right">
    <p>right</p>
    <p>right</p>
  </div>
</div>
```
```css
.box {
  display: table;
  width: 100%;
  table-layout: fixed;(列宽由表格宽度和列宽度设定)
}
.left {
  width: 100px;
  background-color: orange;
  display: table-cell;
}
.right{ 
  background-color: green;
}
```
## 效果图
![20180328164933](https://user-images.githubusercontent.com/22436601/38018626-05c97d26-32a8-11e8-8a80-5301d2faf83f.png)

**好处：同时实现了等高布局**
**坏处：暂无**

## 3、flex

```html
<div class="box">
  <div class="left">
    left
  </div>
  <div class="right">
    <p>right</p>
    <p>right</p>
  </div>
</div>
```
```css
.box {
  display: flex;
}
.left {
  width: 100px;
  background-color: orange;
}
.right{
  flex: 1;
  background-color: green;
}
```
## 效果图
![20180328164933](https://user-images.githubusercontent.com/22436601/38018626-05c97d26-32a8-11e8-8a80-5301d2faf83f.png)

**好处：代码简便，元素变少，方便，强大**
**坏处：不兼容低版本的浏览器**

# 两列定宽+一列自适应
  ## 1、flex

```html
<div class="box">
  <div class="left">
    left
  </div>
  <div class="center">
    center
  </div>
  <div class="right">
    right
  </div>
</div>
```
```css
.box {
  display: flex;
}
.left {
  width: 100px;
  background-color: orange;
}
.center {
  width: 100px;
  background-color: #ccc;
}
.right{
  flex: 1;
  background-color: green;
}
```
## 效果图
![933](https://user-images.githubusercontent.com/22436601/38019420-154632c4-32aa-11e8-9137-571108ce0839.png)

2、float+overflow(或margin)
**原理：左边两个定宽，右面overflow（100+100+overflow）**
**原理：左边两个定宽，右边margin-left: 200px**

## 效果图
![image](https://user-images.githubusercontent.com/22436601/38019819-39975c9c-32ab-11e8-937e-96e9a7e3cf31.png)

# 不定宽+自适应

## 1、float+overflow
**原理:不设置宽度，通过内容将左边的框撑开,最右边通过BFC自适应**
**影响: 如果没有内容，盒子撑不开，可以给盒子设置一个min-midth**

##  效果图
![image](https://user-images.githubusercontent.com/22436601/38020282-664c22d0-32ac-11e8-823c-e5e639f5a72c.png)

#  有间隙的等分布局

## 1、float
**原理: 设置列表宽度并且浮动脱离文档,在通过margin负值改变父元的宽度**

```html
<div class="box">
  <ul>
    <li><p>sadasdasd</p></li>
    <li><p>sadasdasd</p></li>
    <li><p>sadasdasd</p></li>
    <li><p>sadasdasd</p></li>
  </ul>
</div>
```
```css
.box {
  margin-left: -20px;
  background-color: green;
  overflow: hidden;
}
li {
  float: left;
  width: 25%;
  box-sizing: border-box;
  background-color: orange;
  text-align: center;
  padding-left: 20px;
}
p {
  background-color: #fff;
}
```
## 效果图
![image](https://user-images.githubusercontent.com/22436601/38064711-203abb90-3332-11e8-8766-ec5a61d68843.png)

## 2、table
```html
<div class="box">
  <ul>
    <li><p>sadasdasd</p></li>
    <li><p>sadasdasd</p></li>
    <li><p>sadasdasd</p></li>
    <li><p>sadasdasd</p></li>
  </ul>
</div>
```
```css
.box {
  margin-left: -20px;
  background-color: green;
  overflow: hidden;
}
ul {
  display: table;
  width: 100%;
  table-layout: fixed;
}
li {
  display: table-cell;
  background-color: orange;
  text-align: center;
  padding-left: 20px;
}
p {
  background-color: #fff;
}
```
## 效果图
![image](https://user-images.githubusercontent.com/22436601/38064711-203abb90-3332-11e8-8766-ec5a61d68843.png)

## 3、flex
```html
<div class="box">
  <ul>
    <li><p>sadasdasd</p></li>
    <li><p>sadasdasd</p></li>
    <li><p>sadasdasd</p></li>
    <li><p>sadasdasd</p></li>
  </ul>
</div>
```
```css
.box {
  background-color: green;
  overflow: hidden;
}
ul {
  display: flex;
   
}
li {
  flex: 1;
  background-color: orange;
  text-align: center;
  padding-left: 20px;
  &:first-child {
    padding-left: 0;
  }
}
p {
  background-color: #fff;
}
```
## 效果图

![image](https://user-images.githubusercontent.com/22436601/38064711-203abb90-3332-11e8-8766-ec5a61d68843.png)

**优势: 功能能强大**

# 左边定宽+右边自适应的等高布局

## 1、float+padding+margin负值

**原理：通过padding增加盒子的高度，在通过margin负值改变margin的显示区域。任意一个子容器的高度增加，会把父容器撑开到最高那列的高度，其它比这列矮的子容器会通过padding-bottom来补偿这部分的高度差，因为背景和边框都是随着padding变化的**

```html
<div class="box">
  <div class="left">
    <ul>
      <li>left</li>
    </ul>
  </div>
  <div class="right">
    <ul>
      <li>right</li>
      <li>right</li>
    </ul>
  </div>
</div>
```
```css
.box {
  overflow: hidden;
  background-color: #ccc;
}
.left,.right {
  padding-bottom: 9999px;
  margin-bottom: -9999px;
}
.left {
  width: 100px;
  float: left;
  margin-right: 20px;
  background-color: orange;
}
.right {
  overflow: hidden;
  background-color: green;
}
```
## 效果图
![image](https://user-images.githubusercontent.com/22436601/38066938-c6e51116-333c-11e8-907c-c04e1e028b0d.png)

**优势: 兼容性好**
**劣势: 伪等高，不是真正意义上的等高**

## 2、table

```html
<div class="box">
  <div class="left">
    <ul>
      <li>left</li>
    </ul>
  </div>
  <div class="right">
    <ul>
      <li>right</li>
      <li>right</li>
    </ul>
  </div>
</div>
```
```css
.box {
  overflow: hidden;
  display: table;
  width: 100%;
}
.left,.right {
  display: table-cell;
}
.left {
  width: 100px;
  background-color: orange;
}
.right {
  overflow: hidden;
  background-color: green;
}
```
## 效果图
![image](https://user-images.githubusercontent.com/22436601/38067082-6d653890-333d-11e8-8b64-ea0745f1ca15.png)

## 3、flex

```html
<div class="box">
  <div class="left">
    <ul>
      <li>left</li>
    </ul>
  </div>
  <div class="right">
    <ul>
      <li>right</li>
      <li>right</li>
    </ul>
  </div>
</div>
```
```css
.box {
  overflow: hidden;
  display: flex;
  background-color: #ccc;
}
.left {
  width: 100px;
  margin-right: 20px;
  background-color: orange;
}
.right {
  flex: 1;
  background-color: green;
}
```
## 效果图
![image](https://user-images.githubusercontent.com/22436601/38067208-f77a24fa-333d-11e8-97c7-0b3c85e4b1aa.png)

## 4、display

```html
<div class="box">
  <div class="left">
    <ul>
      <li>left</li>
    </ul>
  </div>
  <div class="right">
    <ul>
      <li>right</li>
      <li>right</li>
    </ul>
  </div>
</div>
```
```css
.box {
  overflow: hidden;
  display: -webkit-box;
  background-color: #ccc;
}
.left {
  width: 100px;
  margin-right: 20px;
  background-color: orange;
}
.right {
  -webkit-box-flex: 1;
  background-color: green;
}
```
## 效果图
![image](https://user-images.githubusercontent.com/22436601/38067208-f77a24fa-333d-11e8-97c7-0b3c85e4b1aa.png)

**劣势: 兼容性有极大的问题,只支持webkit内核的高版本浏览器**

# 全屏布局
 ## 1、position

**原理:全屏脱离文档流，通过absolute的定位拉伸盒子，右边的自适应通过BFC不影响外面的元素，左边的定宽**

```html
<div class="parent"> 
 <div class="top">
   top 
 </div> 
 <div class="left">
   left 
 </div> 
 <div class="right"> 
  <div class="inner">
    right 
  </div> 
 </div> 
 <div class="bottom">
   bottom 
 </div> 
</div>
```
```css
html,body,.parent {
	margin: 0;
	height: 100%;
	overflow: hidden;
}

body {
	color: white;
}

.top {
	position: absolute;
	top: 0;
	left: 0;
	right: 0;
	height: 100px;
	background: blue;
}

.left {
	position: absolute;
	left: 0;
	top: 100px;
	bottom: 50px;
	width: 200px;
	background: red;
}

.right {
	position: absolute;
	left: 200px;
	top: 100px;
	bottom: 50px;
	right: 0;
	background: pink;
	overflow: auto;
}

.right .inner {
	min-height: 1000px;
}

.bottom {
	position: absolute;
	left: 0;
	right: 0;
	bottom: 0;
	height: 50px;
	background: black;
}
```
##  效果图
![image](https://user-images.githubusercontent.com/22436601/38068213-948a7afc-3342-11e8-81fe-5100571f159f.png)

## 2、flex

```html
<div class="parent"> 
 <div class="top">
   top 
 </div> 
 <div class="middle"> 
  <div class="left">
    left 
  </div> 
  <div class="right"> 
   <div class="inner">
     right 
   </div> 
  </div> 
 </div> 
 <div class="bottom">
   bottom 
 </div> 
</div>
```
```scss
html,body,.parent {
	margin: 0;
	height: 100%;
	overflow: hidden;
}

body {
	color: white;
}
.parent {
  display: flex;
  flex-direction: column;//主轴为垂直方向
}
.top{
  height:100px;
  background: orange;
}
.middle {
   flex: 1;
   display: inline-flex;//或flex
  .left {
    width: 200px;
    background-color: #ccc;
  }
  .right {
    flex: 1;
    background-color: #89afd7;
    overflow: auto;
    .inner{
      min-height: 1000px;
    }
  }
}
.bottom {
  height: 100px;
  background-color: green;
}
```
## 效果图
![image](https://user-images.githubusercontent.com/22436601/38068583-90349b98-3344-11e8-8d6a-39d19167bb7c.png)

# 查阅
![image](https://user-images.githubusercontent.com/22436601/38068596-a1c280f0-3344-11e8-8f4b-de425ce5f4a1.png)
